(()=>{
 "use strict";
 const panel=document.getElementById('adminPanel'),menu=document.querySelector('.adminMenu');if(!panel||!menu||!window.SOS)return;
 const uid=()=>crypto.randomUUID?.()||`id-${Date.now()}-${Math.random().toString(16).slice(2)}`;
 const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
 const musicState=v=>v>=100?'Completed':v<=0?'Not started':'In progress';
 function eventsPanel(){const items=SOS.read('sos_events_v1',[]);panel.innerHTML=`<div class="adminSectionHead"><div><p class="sectionEyebrow">Live Calendar</p><h2>Events Manager</h2></div></div><p class="adminLead">Publish shows, livestreams, release parties, appearances, and festival dates directly to the Events page.</p><form class="appForm adminEditor" id="eventManagerForm"><div class="formRow"><label>Event title<input name="title" required></label><label>Event type<select name="type"><option>Live Show</option><option>Festival</option><option>Livestream</option><option>Release Event</option><option>Meet & Greet</option><option>Appearance</option></select></label></div><div class="formRow"><label>Date and time<input name="date" type="datetime-local" required></label><label>Venue<input name="venue" placeholder="Venue or platform"></label></div><div class="formRow"><label>City / location<input name="city"></label><label>Details link<input name="link" placeholder="https://..."></label></div><label>Description<textarea name="description"></textarea></label><button class="primaryButton">Publish Event</button></form><div class="adminEventGrid">${items.length?items.slice().reverse().map(e=>`<article class="eventAdminCard"><p class="sectionEyebrow">${esc(e.type)}</p><h3>${esc(e.title)}</h3><div class="eventAdminMeta">${new Date(e.date).toLocaleString()} • ${esc(e.venue||'TBA')}</div><p>${esc(e.description||'')}</p><div class="adminItemActions"><button class="smallAction" data-toggle-event="${e.id}">${e.active===false?'Show':'Hide'}</button><button class="smallAction dangerAction" data-delete-event="${e.id}">Delete</button></div></article>`).join(''):'<div class="emptyState">No custom events yet.</div>'}</div>`;document.getElementById('eventManagerForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),arr=SOS.read('sos_events_v1',[]);arr.push({id:uid(),title:f.get('title').trim(),type:f.get('type'),date:f.get('date'),venue:f.get('venue').trim(),city:f.get('city').trim(),link:f.get('link').trim(),description:f.get('description').trim(),active:true,createdAt:Date.now()});SOS.write('sos_events_v1',arr);SOS.toast('Event published to the Events page.',{title:'Events Manager'});eventsPanel()}}
 function readCollabThreads(){const value=SOS.read('sos_collab_threads_v1',{});return value&&typeof value==='object'&&!Array.isArray(value)?value:{}}
 function collabThreadKey(projectId){return `project::${projectId}`}
 function collaborationsPanel(){
  const users=SOS.read(SOS.K.users,[]),projects=SOS.read('sos_collab_projects_v1',[]),threads=readCollabThreads(),approved=users.filter(u=>u.role==='admin'||u.collaborationAccess);
  const messageRows=[];
  projects.forEach(project=>{
   const rows=Array.isArray(threads[collabThreadKey(project.id)])?threads[collabThreadKey(project.id)]:[];
   rows.slice().reverse().forEach(message=>messageRows.push({project,message}));
  });
  panel.innerHTML=`<div class="adminSectionHead"><div><p class="sectionEyebrow">Private Studio</p><h2>Collaboration Teams</h2></div><a class="smallAction" href="collaboration.html">Open Studio ↗</a></div><p class="adminLead">Approve members for Collaboration Studio, review every project, and remove collaboration projects or individual project posts directly from the Admin Hub.</p><section class="adminCollabRoster"><div class="adminSectionHead compact"><div><p class="sectionEyebrow">Access Directory</p><h3>People with studio access</h3></div><span class="statusPill">${approved.length} approved</span></div><div class="adminCollabRosterGrid">${users.length?users.map(u=>{const projectCount=projects.filter(p=>(p.memberIds||[]).includes(u.id)).length;const active=u.role==='admin'||u.collaborationAccess;return`<article class="adminCollabPerson ${active?'hasAccess':'noAccess'}"><img src="${esc(u.avatar||'assets/images/sos-logo.png')}" alt=""><div><strong>${esc(u.displayName)}</strong><small>${esc(u.role)} • ${projectCount} project${projectCount===1?'':'s'}</small></div><span>${active?'Access enabled':'No access'}</span>${u.role!=='admin'?`<button class="smallAction" data-collab-roster-toggle="${u.id}">${active?'Remove access':'Grant access'}</button>`:'<span class="statusPill">Permanent</span>'}</article>`}).join(''):'<div class="emptyState">No member accounts yet.</div>'}</div></section>
  <section class="adminCollabManageSection"><div class="adminSectionHead compact"><div><p class="sectionEyebrow">Project Moderation</p><h3>Projects and posts</h3></div><span class="statusPill">${projects.length} project${projects.length===1?'':'s'}</span></div><div class="adminProgressGrid">${projects.length?projects.map(p=>{const members=(p.memberIds||[]).map(id=>users.find(u=>u.id===id)?.displayName).filter(Boolean);const val=Number(p.progress||0);const rows=Array.isArray(threads[collabThreadKey(p.id)])?threads[collabThreadKey(p.id)]:[];return`<article class="musicAdminProgressCard adminCollabProjectCard"><div class="adminCollabProjectTop"><div><p class="sectionEyebrow">${esc(p.status||'Idea')}</p><h3>${esc(p.title||'Untitled Project')}</h3></div><span class="statusPill">${rows.length} post${rows.length===1?'':'s'}</span></div><p>${esc(members.join(' • ')||'No collaborators')}</p><div class="musicProgressTrack"><i style="width:${val}%"></i></div><span class="musicProgressBadge">${val}% • ${musicState(val)}</span><div class="adminItemActions adminCollabProjectActions"><button class="smallAction dangerAction" data-clear-collab-posts="${esc(p.id)}" ${rows.length?'':'disabled'}>Delete All Posts</button><button class="smallAction dangerAction" data-delete-collab-project="${esc(p.id)}">Delete Project</button></div></article>`}).join(''):'<div class="emptyState">No collaboration projects yet.</div>'}</div></section>
  <section class="adminCollabPostsSection"><div class="adminSectionHead compact"><div><p class="sectionEyebrow">Post Moderation</p><h3>Recent collaboration posts</h3></div><span class="statusPill">${messageRows.length} total</span></div><div class="adminCollabPostsList">${messageRows.length?messageRows.slice(0,60).map(({project,message})=>{const sender=users.find(u=>u.id===message.senderId);const attachment=message.attachment?.name?` • Attachment: ${esc(message.attachment.name)}`:'';return`<article class="adminCollabPostItem" data-open-collab-post="${esc(message.id)}" data-open-collab-project="${esc(project.id)}" tabindex="0" role="link"><div class="adminCollabPostCopy"><div class="adminCollabPostMeta"><strong>${esc(sender?.displayName||message.senderName||'Collaborator')}</strong><span>${esc(project.title||'Untitled Project')}</span></div><p>${esc(message.text||message.message||'(Audio or file post)')}</p><small>${message.createdAt||message.date?new Date(message.createdAt||message.date).toLocaleString():'No date'}${attachment}</small></div><button class="smallAction dangerAction" data-delete-collab-post="${esc(message.id)}" data-collab-project-id="${esc(project.id)}">Delete Post</button></article>`}).join(''):'<div class="emptyState">No collaboration posts yet.</div>'}</div>${messageRows.length>60?`<p class="adminLead">Showing the newest 60 posts for smooth Admin Hub performance.</p>`:''}</section>`
 }
 function enhanceMusic(){const form=document.getElementById('musicForm');if(!form||form.dataset.v36)return;form.dataset.v36='1';const submit=form.querySelector('button[type="submit"],button.primaryButton');submit?.insertAdjacentHTML('beforebegin','<div class="formRow"><label>Completion percentage<input name="progress" type="range" min="0" max="100" value="0" id="musicProgressAdmin"></label><label>Progress state<input id="musicProgressStateAdmin" value="Not started" readonly></label></div><div class="musicProgressTrack"><i id="musicProgressAdminFill" style="width:0%"></i></div>');const range=form.querySelector('#musicProgressAdmin'),state=form.querySelector('#musicProgressStateAdmin'),fill=form.querySelector('#musicProgressAdminFill');range?.addEventListener('input',()=>{state.value=`${range.value}% • ${musicState(Number(range.value))}`;fill.style.width=range.value+'%'});form.addEventListener('submit',()=>{const title=form.elements.title?.value.trim(),progress=Number(range?.value||0);setTimeout(()=>{const arr=SOS.read(SOS.K.music,[]),item=[...arr].reverse().find(x=>x.title===title);if(item){item.progress=progress;item.completionState=musicState(progress);item.completed=progress===100;SOS.write(SOS.K.music,arr)}},0)},true);const list=SOS.read(SOS.K.music,[]);if(list.length){const wrap=document.createElement('div');wrap.className='adminProgressGrid';wrap.innerHTML=list.map(i=>{const v=Number(i.progress??100);return`<article class="musicAdminProgressCard"><h3>${esc(i.title)}</h3><div class="musicProgressTrack"><i style="width:${v}%"></i></div><span class="musicProgressBadge">${v}% • ${musicState(v)}</span></article>`}).join('');form.after(wrap)}}
 function enhanceAnnouncements(){const form=document.getElementById('announcementForm');if(!form||form.dataset.v36)return;form.dataset.v36='1';const button=form.querySelector('button[type="submit"],button.primaryButton');button?.insertAdjacentHTML('beforebegin','<div class="formRow"><label>Cycle timer (seconds)<input name="cycleSeconds" type="number" min="5" max="600" value="20"></label><label>Timer preview<input value="Floating card with countdown" readonly></label></div>');form.addEventListener('submit',()=>{const title=form.elements.title?.value.trim(),seconds=Math.max(5,Number(form.elements.cycleSeconds?.value||20));setTimeout(()=>{const arr=SOS.read(SOS.K.announcements,[]),item=[...arr].reverse().find(x=>x.title===title);if(item){item.cycleSeconds=seconds;SOS.write(SOS.K.announcements,arr);localStorage.removeItem('sos_seen_announcements_v1')}},0)},true)}
 menu.addEventListener('click',e=>{const b=e.target.closest('[data-panel]');if(!b)return;setTimeout(()=>{if(b.dataset.panel==='events')eventsPanel();else if(b.dataset.panel==='collaborations')collaborationsPanel();else if(b.dataset.panel==='music')enhanceMusic();else if(b.dataset.panel==='announcements')enhanceAnnouncements()},0)});
 panel.addEventListener('click',e=>{let open=e.target.closest('[data-open-collab-post]');if(open&&!e.target.closest('button,a,input,select,textarea')){localStorage.setItem('sos_collab_admin_target_v1',JSON.stringify({projectId:open.dataset.openCollabProject,messageId:open.dataset.openCollabPost,at:Date.now()}));location.href='collaboration.html';return}let b=e.target.closest('[data-collab-roster-toggle]');if(b){const users=SOS.read(SOS.K.users,[]),u=users.find(x=>x.id===b.dataset.collabRosterToggle);if(u&&u.role!=='admin'){u.collaborationAccess=!u.collaborationAccess;SOS.write(SOS.K.users,users);if(u.collaborationAccess){const notes=SOS.read(SOS.K.notifications,[]);notes.push({id:uid(),userId:u.id,title:'Collaboration access unlocked',message:'You now have access to Collaboration Studio. Check your profile to enter.',icon:'🤝',link:'members.html',seen:false});SOS.write(SOS.K.notifications,notes)}SOS.toast(u.collaborationAccess?'Collaboration access granted.':'Collaboration access removed.',{title:'Studio Access'});collaborationsPanel()}return}b=e.target.closest('[data-delete-collab-post]');if(b){const threads=readCollabThreads(),key=collabThreadKey(b.dataset.collabProjectId);threads[key]=(Array.isArray(threads[key])?threads[key]:[]).filter(message=>message.id!==b.dataset.deleteCollabPost);SOS.write('sos_collab_threads_v1',threads);SOS.toast('Collaboration post deleted.',{title:'Collaboration Moderation'});collaborationsPanel();return}b=e.target.closest('[data-clear-collab-posts]');if(b){const threads=readCollabThreads();threads[collabThreadKey(b.dataset.clearCollabPosts)]=[];SOS.write('sos_collab_threads_v1',threads);SOS.toast('All posts in this project were deleted.',{title:'Collaboration Moderation'});collaborationsPanel();return}b=e.target.closest('[data-delete-collab-project]');if(b){const projectId=b.dataset.deleteCollabProject;SOS.write('sos_collab_projects_v1',SOS.read('sos_collab_projects_v1',[]).filter(project=>project.id!==projectId));const threads=readCollabThreads();delete threads[collabThreadKey(projectId)];SOS.write('sos_collab_threads_v1',threads);SOS.toast('Collaboration project and its posts were deleted.',{title:'Collaboration Moderation'});collaborationsPanel();return}b=e.target.closest('[data-delete-event]');if(b){SOS.write('sos_events_v1',SOS.read('sos_events_v1',[]).filter(x=>x.id!==b.dataset.deleteEvent));eventsPanel();return}b=e.target.closest('[data-toggle-event]');if(b){const arr=SOS.read('sos_events_v1',[]),item=arr.find(x=>x.id===b.dataset.toggleEvent);if(item)item.active=item.active===false;SOS.write('sos_events_v1',arr);eventsPanel()}});
 const obs=new MutationObserver(()=>{enhanceMusic();enhanceAnnouncements()});obs.observe(panel,{childList:true,subtree:false});
})();
