(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const toast=(m,t='Forums')=>window.SOS?.toast?.(m,{title:t})||alert(m);
const client=()=>window.SOS_SUPABASE?.client;
const state={categories:[],topics:[],replies:new Map(),reactions:[],active:'all',tag:'',query:'',sort:'newest',replying:'',selectedTags:new Set(),file:null,user:null,profile:null};
const defaultAvatar='assets/images/sos-logo.png';
const canStaff=()=>['owner','administrator','moderator'].includes(state.profile?.role);
const cleanTag=v=>String(v||'').toLowerCase().trim().replace(/^#/,'').replace(/[^a-z0-9-]/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'').slice(0,24);
const formatDate=v=>new Date(v).toLocaleString();

async function auth(){
 const {data}=await client().auth.getSession(); state.user=data.session?.user||null;
 if(state.user){const {data:p}=await client().from('profiles').select('*').eq('id',state.user.id).maybeSingle();state.profile=p||null;}
}
async function load(){
 if(!client())return toast('Supabase is not connected.','Forum unavailable');
 await auth();
 const [{data:cats,error:ce},{data:topics,error:te},{data:react,error:re}]=await Promise.all([
  client().from('forum_categories').select('*').eq('is_visible',true).order('sort_order'),
  client().from('forum_topics').select('*,category:forum_categories(*),author:profiles!forum_topics_author_id_fkey(id,username,display_name,avatar_url,role,rank_name)').eq('is_hidden',false).order('is_pinned',{ascending:false}).order('last_activity_at',{ascending:false}),
  client().from('forum_reactions').select('*').eq('reaction','heart')
 ]);
 if(ce||te||re){console.error(ce||te||re);return toast((ce||te||re).message,'Forum load failed');}
 state.categories=cats||[];state.topics=topics||[];state.reactions=react||[];
 const ids=state.topics.map(t=>t.id);
 if(ids.length){
  const {data,error}=await client().from('forum_replies').select('*,author:profiles!forum_replies_author_id_fkey(id,username,display_name,avatar_url,role,rank_name)').in('topic_id',ids).eq('is_hidden',false).order('created_at');
  if(error)console.error(error); else (data||[]).forEach(r=>{const a=state.replies.get(r.topic_id)||[];a.push(r);state.replies.set(r.topic_id,a)});
 }
 syncCategorySelect();draw();
}
function syncCategorySelect(){const s=$('#postCategory');if(!s)return;s.innerHTML=state.categories.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');}
function filtered(){let list=[...state.topics];if(state.active!=='all')list=list.filter(t=>t.category_id===state.active);if(state.tag)list=list.filter(t=>(t.tags||[]).includes(state.tag));if(state.query){const q=state.query.toLowerCase();list=list.filter(t=>`${t.title} ${t.body} ${(t.tags||[]).join(' ')} ${t.author?.display_name||t.author?.username||''}`.toLowerCase().includes(q));}if(state.sort==='oldest')list.sort((a,b)=>new Date(a.created_at)-new Date(b.created_at));if(state.sort==='popular')list.sort((a,b)=>reactionCount(b.id)-reactionCount(a.id));if(state.sort==='replied')list.sort((a,b)=>(state.replies.get(b.id)?.length||0)-(state.replies.get(a.id)?.length||0));if(state.sort==='updated')list.sort((a,b)=>new Date(b.last_activity_at)-new Date(a.last_activity_at));return list;}
const reactionCount=id=>state.reactions.filter(r=>r.topic_id===id).length;
const reacted=id=>state.reactions.some(r=>r.topic_id===id&&r.user_id===state.user?.id);
function drawCats(){const el=$('#forumCategories');if(!el)return;el.innerHTML=[{id:'all',name:'All Discussions'},...state.categories].map(c=>`<button class="categoryButton ${state.active===c.id?'active':''}" data-category="${c.id}"><span>${esc(c.name)}</span><small>${c.id==='all'?state.topics.length:state.topics.filter(t=>t.category_id===c.id).length}</small></button>`).join('');}
function drawTags(){const counts={};state.topics.forEach(t=>(t.tags||[]).forEach(x=>counts[x]=(counts[x]||0)+1));$('#forumTagCloud').innerHTML=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,20).map(([t,n])=>`<button class="forumTag ${state.tag===t?'active':''}" data-tag="${esc(t)}">#${esc(t)} <small>${n}</small></button>`).join('')||'<span class="postMeta">Tags appear after members publish posts.</span>';$('#activeTagRow').innerHTML=state.tag?`<span>Filtering by <strong>#${esc(state.tag)}</strong></span><button class="smallAction" data-clear-tag>Clear tag</button>`:'';}
function replyForm(t){return state.replying===t.id?`<form class="inlineReplyComposer" data-reply-form="${t.id}"><textarea maxlength="30000" required placeholder="Write your reply..."></textarea><div class="composerActions"><button class="smallAction" type="button" data-cancel-reply>Cancel</button><button class="primaryButton">Post Reply</button></div></form>`:'';}
function media(t){let out='';if(t.image_url)out+=`<div class="postMedia"><img src="${esc(t.image_url)}" alt="Forum attachment"></div>`;if(t.media_url)out+=`<p><a class="smallAction" href="${esc(t.media_url)}" target="_blank" rel="noopener">Open shared media ↗</a></p>`;return out;}
function draw(){drawCats();drawTags();const list=filtered();$('#postList').innerHTML=list.length?list.map(t=>{const reps=state.replies.get(t.id)||[],author=t.author||{},mine=state.user?.id===t.author_id;return `<article class="forumPost ${t.is_pinned?'forumPostPinned':''} ${t.is_locked?'forumPostLocked':''}" data-post-id="${t.id}">${t.is_pinned?'<div class="pinnedRibbon"><span>📌</span><strong>Pinned Discussion</strong></div>':''}${t.is_locked?'<div class="lockedRibbon">🔒 Replies locked by staff</div>':''}<div class="postTop"><button class="forumAvatarButton" type="button"><img class="avatar" src="${esc(author.avatar_url||defaultAvatar)}" alt="${esc(author.display_name||author.username||'Member')}"></button><div class="postIdentity"><h3>${esc(t.title)}</h3><div class="postMeta">${esc(author.display_name||author.username||'Member')} • ${esc(t.category?.name||'Forum')} • ${formatDate(t.created_at)}</div></div></div><div class="postTags">${(t.tags||[]).map(x=>`<button data-tag="${esc(x)}">#${esc(x)}</button>`).join('')}</div><div class="postBody">${esc(t.body).replace(/\n/g,'<br>')}</div>${media(t)}<div class="postActions"><button class="smallAction forumHeartReaction ${reacted(t.id)?'is-reacted':''}" data-like="${t.id}"><span class="forumHeartIcon">${reacted(t.id)?'♥':'♡'}</span><span class="forumHeartCount">${reactionCount(t.id)}</span><span>${reacted(t.id)?'Loved':'Love'}</span></button><button class="smallAction" data-reply="${t.id}" ${t.is_locked&&!canStaff()?'disabled':''}>Reply (${reps.length})</button>${mine||canStaff()?`<button class="smallAction dangerAction" data-delete="${t.id}">Delete</button>`:''}${canStaff()?`<button class="smallAction" data-pin="${t.id}">${t.is_pinned?'Unpin':'Pin'}</button><button class="smallAction" data-lock="${t.id}">${t.is_locked?'Unlock':'Lock'}</button>`:''}</div>${replyForm(t)}${reps.map(r=>`<div class="forumReply"><img class="avatar" src="${esc(r.author?.avatar_url||defaultAvatar)}" alt=""><div class="forumReplyContent"><div class="forumReplyHeading"><div><button class="forumAuthorLink">${esc(r.author?.display_name||r.author?.username||'Member')}</button><span class="forumReplyDate">${formatDate(r.created_at)}</span></div>${state.user?.id===r.author_id||canStaff()?`<button class="replyDeleteButton" data-delete-reply="${r.id}">Delete reply</button>`:''}</div><p>${esc(r.body).replace(/\n/g,'<br>')}</p></div></div>`).join('')}</article>`}).join(''):'<div class="emptyState">No forum posts matched your filters.</div>';}
async function upload(file,topicId){if(!file)return null;const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`${state.user.id}/${topicId}/${crypto.randomUUID()}.${ext}`;const {error}=await client().storage.from('forum-attachments').upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;const {data}=client().storage.from('forum-attachments').getPublicUrl(path);await client().from('attachments').insert({owner_id:state.user.id,topic_id:topicId,bucket:'forum-attachments',storage_path:path,file_name:file.name,mime_type:file.type,size_bytes:file.size});return data.publicUrl;}
async function createTopic(e){e.preventDefault();if(!state.user)return toast('Please sign in before creating a post.','Members only');const f=new FormData(e.currentTarget),title=String(f.get('title')||'').trim(),body=String(f.get('body')||'').trim();try{const {data,error}=await client().from('forum_topics').insert({category_id:f.get('category'),author_id:state.user.id,title,body,tags:[...state.selectedTags],subcategory:f.get('subcategory')||'',media_url:f.get('mediaUrl')||null}).select().single();if(error)throw error;if(state.file){const image=await upload(state.file,data.id);const {error:u}=await client().from('forum_topics').update({image_url:image}).eq('id',data.id);if(u)throw u;}localStorage.removeItem('sos_forum_draft_v2');e.currentTarget.reset();state.selectedTags.clear();state.file=null;$('#forumComposer').hidden=true;toast('Your discussion is now live.','Post published');state.replies.clear();await load();}catch(err){console.error(err);toast(err.message,'Could not publish');}}
async function act(target){const id=target.dataset.like||target.dataset.delete||target.dataset.reply||target.dataset.pin||target.dataset.lock;if(target.dataset.reply){if(!state.user)return toast('Sign in to reply.','Members only');state.replying=state.replying===id?'':id;return draw();}if(target.dataset.like){if(!state.user)return toast('Sign in to react.','Members only');const row=state.reactions.find(r=>r.topic_id===id&&r.user_id===state.user.id);const q=row?client().from('forum_reactions').delete().eq('id',row.id):client().from('forum_reactions').insert({user_id:state.user.id,topic_id:id,reaction:'heart'});const {error}=await q;if(error)return toast(error.message,'Reaction failed');return load();}if(target.dataset.delete){if(!confirm('Delete this discussion and all replies?'))return;const {error}=await client().from('forum_topics').delete().eq('id',id);if(error)return toast(error.message,'Delete failed');return load();}if(target.dataset.pin||target.dataset.lock){const topic=state.topics.find(t=>t.id===id),changes=target.dataset.pin?{is_pinned:!topic.is_pinned}:{is_locked:!topic.is_locked};const {error}=await client().rpc('forum_set_topic_moderation',{target_topic:id,pin_value:target.dataset.pin?changes.is_pinned:null,lock_value:target.dataset.lock?changes.is_locked:null});if(error)return toast(error.message,'Moderation failed');return load();}if(target.dataset.deleteReply){if(!confirm('Delete this reply?'))return;const {error}=await client().from('forum_replies').delete().eq('id',target.dataset.deleteReply);if(error)return toast(error.message,'Delete failed');state.replies.clear();return load();}}
async function submitReply(form){if(!state.user)return toast('Sign in to reply.','Members only');const topic=state.topics.find(t=>t.id===form.dataset.replyForm),body=$('textarea',form).value.trim();if(topic?.is_locked&&!canStaff())return toast('This topic is locked.','Replies unavailable');const {error}=await client().from('forum_replies').insert({topic_id:topic.id,author_id:state.user.id,body});if(error)return toast(error.message,'Reply failed');await client().from('forum_topics').update({last_activity_at:new Date().toISOString()}).eq('id',topic.id);state.replying='';state.replies.clear();toast('Your reply is now live.','Reply posted');load();}
function bind(){
 $('#newPostButton').onclick=()=>{if(!state.user)return toast('Please sign in before creating a post.','Members only');$('#forumComposer').hidden=false;$('#forumComposer').scrollIntoView({behavior:'smooth'});};$('#closeComposer').onclick=()=>$('#forumComposer').hidden=true;$('#postForm').onsubmit=createTopic;
 $('#postImage').onchange=e=>{state.file=e.target.files[0]||null;const p=$('#imagePreview');if(state.file){p.hidden=false;p.innerHTML=`<strong>${esc(state.file.name)}</strong><p class="postMeta">Ready to upload securely to Supabase Storage.</p>`}else p.hidden=true;};
 $('#forumCategories').onclick=e=>{const b=e.target.closest('[data-category]');if(b){state.active=b.dataset.category;draw();}};$('#forumTagCloud').onclick=e=>{const b=e.target.closest('[data-tag]');if(b){state.tag=b.dataset.tag;draw();}};$('#activeTagRow').onclick=e=>{if(e.target.closest('[data-clear-tag]')){state.tag='';draw();}};$('#forumSearch').oninput=e=>{state.query=e.target.value;draw();};$('#forumSort').onchange=e=>{state.sort=e.target.value;draw();};
 $('#postList').onclick=e=>{const tag=e.target.closest('[data-tag]');if(tag){state.tag=tag.dataset.tag;return draw();}const a=e.target.closest('[data-like],[data-delete],[data-reply],[data-pin],[data-lock],[data-delete-reply],[data-cancel-reply]');if(a?.dataset.cancelReply!==undefined){state.replying='';return draw();}if(a)act(a);};$('#postList').onsubmit=e=>{const f=e.target.closest('[data-reply-form]');if(f){e.preventDefault();submitReply(f);}};
 const custom=$('#customTagInput');$('#addCustomTag').onclick=()=>{const t=cleanTag(custom.value);if(t&&state.selectedTags.size<8)state.selectedTags.add(t);custom.value='';renderSelected();};custom.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();$('#addCustomTag').click();}};$('#suggestedTagButtons').innerHTML=['community','edm','production','dj-tips','feedback','events','help','collaboration'].map(t=>`<button type="button" class="tagChoice" data-pick-tag="${t}">#${t}</button>`).join('');$('#suggestedTagButtons').onclick=e=>{const b=e.target.closest('[data-pick-tag]');if(!b)return;const t=b.dataset.pickTag;state.selectedTags.has(t)?state.selectedTags.delete(t):state.selectedTags.size<8&&state.selectedTags.add(t);renderSelected();};
 $('#saveDraftButton').onclick=()=>{const f=new FormData($('#postForm'));localStorage.setItem('sos_forum_draft_v2',JSON.stringify({category:f.get('category'),title:f.get('title'),body:f.get('body'),mediaUrl:f.get('mediaUrl'),tags:[...state.selectedTags]}));toast('Draft saved in this browser.','Draft saved');};
}
function renderSelected(){$('#selectedTagChips').innerHTML=state.selectedTags.size?[...state.selectedTags].map(t=>`<span class="selectedTagChip">#${esc(t)}</span>`).join(''):'<span class="postMeta">Select up to 8 tags.</span>';}
document.addEventListener('DOMContentLoaded',async()=>{bind();renderSelected();await load();client().auth.onAuthStateChange(()=>{state.replies.clear();load();});client().channel('forum-live').on('postgres_changes',{event:'*',schema:'public',table:'forum_topics'},()=>{state.replies.clear();load();}).on('postgres_changes',{event:'*',schema:'public',table:'forum_replies'},()=>{state.replies.clear();load();}).subscribe();});
})();
