/* Seeker Of SoundZ v4.10 — Universal Command Search */
(()=>{"use strict";
const PAGES=[
["Home","index.html","main homepage sos dj producer creator frequency"],["About Seeker Of SoundZ","about.html","biography artist story dj producer"],["Music","music.html","tracks releases songs audio mixes download"],["Producer Hub & Plugins","producer-hub.html","plugins fl studio samples presets tools dj software"],["Gallery","gallery.html","photos headshots live events production images"],["Videos & YouTube","videos.html","youtube videos live sets reels sessions"],["Merch Store","merch.html","hoodie shirt hat apparel clothing music products store"],["Forums","forums.html","community posts replies tags discussions"],["Members Dashboard","members.html","profile settings dashboard vip achievements"],["Collaboration Studio","collaboration.html","projects teams messages production collaboration"],["Events","events.html","shows performances livestream schedule"],["Socials","socials.html","youtube instagram soundcloud twitch links"],["Contact","contact.html","booking message inquiry collaboration"],["Admin Hub","admin.html","admin management announcements merch teams diagnostics"]];
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let open=false,items=[];
function read(k,f=[]){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
function discover(){items=PAGES.map(([title,url,keywords])=>({title,url,keywords,type:"Page",icon:"↗"}));const K=window.SOS?.K||{};const products=K.catalog?window.SOS.read(K.catalog,[]):[];products.forEach(p=>items.push({title:p.name||"Merch item",url:`merch.html?search=${encodeURIComponent(p.name||"")}`,keywords:[p.description,p.category,p.type,p.sizes,p.colors,p.tags].flat().join(" "),type:"Merch",icon:"◇"}));const posts=K.posts?window.SOS.read(K.posts,[]):[];posts.forEach(p=>items.push({title:p.title||"Forum post",url:`forums.html?post=${encodeURIComponent(p.id)}`,keywords:[p.body,p.author,p.category,...(p.tags||[])].join(" "),type:"Forum",icon:"#"}));const resources=read("sos_producer_resources_v1",[]);resources.forEach(r=>items.push({title:r.name,url:"producer-hub.html",keywords:[r.vendor,r.type,r.category,r.ecosystem,r.description,...(r.tags||[])].join(" "),type:"Plugin",icon:"⌁"}));return items}
function create(){if(document.getElementById("sosGlobalSearch"))return;const wrap=document.createElement("div");wrap.id="sosGlobalSearch";wrap.className="sosGlobalSearch";wrap.hidden=true;wrap.innerHTML=`<div class="globalSearchBackdrop" data-search-close></div><section class="globalSearchPanel" role="dialog" aria-modal="true" aria-labelledby="globalSearchTitle"><div class="globalSearchHead"><div><p class="sectionEyebrow">Search the Frequency</p><h2 id="globalSearchTitle">Find anything</h2></div><button type="button" class="globalSearchClose" data-search-close aria-label="Close search">×</button></div><label class="globalSearchInput"><span>⌕</span><input id="globalSearchField" type="search" autocomplete="off" placeholder="Search pages, forum posts, hoodies, music, plugins, YouTube…"><kbd>ESC</kbd></label><div class="globalSearchHints"><button data-search-preset="hoodie">Hoodies</button><button data-search-preset="music">Music</button><button data-search-preset="forums">Forums</button><button data-search-preset="youtube">YouTube</button><button data-search-preset="plugins">Plugins</button></div><div id="globalSearchResults" class="globalSearchResults"></div><footer><span>↑ ↓ navigate</span><span>Enter open</span><span>Esc close</span></footer></section>`;document.body.append(wrap)}
function addButton(){const utility=document.querySelector("#mainNav .navUtility");if(!utility||document.getElementById("globalSearchButton"))return;const b=document.createElement("button");b.id="globalSearchButton";b.className="navIconButton globalSearchButton";b.type="button";b.setAttribute("aria-label","Search entire site");b.title="Search the Frequency (Ctrl/⌘ + K)";b.innerHTML='<span>⌕</span><em>Search</em>';utility.prepend(b)}
function show(){create();discover();const el=document.getElementById("sosGlobalSearch");el.hidden=false;requestAnimationFrame(()=>el.classList.add("open"));document.body.classList.add("globalSearchOpen");open=true;render("");setTimeout(()=>document.getElementById("globalSearchField")?.focus(),60)}
function hide(){const el=document.getElementById("sosGlobalSearch");if(!el)return;el.classList.remove("open");document.body.classList.remove("globalSearchOpen");open=false;setTimeout(()=>el.hidden=true,220)}
function score(it,q){const hay=`${it.title} ${it.keywords} ${it.type}`.toLowerCase(),words=q.toLowerCase().trim().split(/\s+/).filter(Boolean);if(!words.length)return it.type==="Page"?4:1;let s=0;for(const w of words){if(it.title.toLowerCase().includes(w))s+=8;if(hay.includes(w))s+=3;if(it.type.toLowerCase().includes(w))s+=2}return s}
function render(q){const box=document.getElementById("globalSearchResults");if(!box)return;const found=items.map(i=>[i,score(i,q)]).filter(x=>x[1]>0).sort((a,b)=>b[1]-a[1]).slice(0,18).map(x=>x[0]);box.innerHTML=found.length?found.map((it,i)=>`<a class="globalSearchResult ${i===0?"active":""}" href="${esc(it.url)}"><span class="resultIcon">${it.icon}</span><div><strong>${esc(it.title)}</strong><small>${esc(it.type)} · ${esc(it.keywords).slice(0,92)}</small></div><b>↗</b></a>`).join(""):`<div class="globalSearchEmpty"><span>⌁</span><h3>No signal found</h3><p>Try a page name, product, forum topic, artist tool, or category.</p></div>`}
function move(dir){const all=[...document.querySelectorAll('.globalSearchResult')];if(!all.length)return;let i=all.findIndex(x=>x.classList.contains('active'));all[i]?.classList.remove('active');i=(i+dir+all.length)%all.length;all[i].classList.add('active');all[i].scrollIntoView({block:'nearest'})}
document.addEventListener("click",e=>{if(e.target.closest("#globalSearchButton")){open?hide():show();return}if(e.target.closest("[data-search-close]")){hide();return}const p=e.target.closest("[data-search-preset]");if(p){const f=document.getElementById("globalSearchField");f.value=p.dataset.searchPreset;render(f.value);f.focus()}});
document.addEventListener("input",e=>{if(e.target.id==="globalSearchField")render(e.target.value)});
document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();open?hide():show()}if(!open)return;if(e.key==="Escape"){e.preventDefault();hide()}else if(e.key==="ArrowDown"){e.preventDefault();move(1)}else if(e.key==="ArrowUp"){e.preventDefault();move(-1)}else if(e.key==="Enter"){const a=document.querySelector('.globalSearchResult.active');if(a){e.preventDefault();location.href=a.href}}});
const init=()=>{create();addButton()};window.addEventListener("load",init);new MutationObserver(addButton).observe(document.documentElement,{childList:true,subtree:true});
})();