(()=>{
"use strict";
const A=document.getElementById('authArea'),D=document.getElementById('memberDashboard');if(!A)return;
const DEMOS=[
 {id:'demo-admin',displayName:'Demo Admin',email:'admin@seeker.local',password:'admin123',avatar:'assets/images/sos-logo.png',role:'admin',paidMember:true},
 {id:'demo-member',displayName:'Demo Member',email:'member@seeker.local',password:'member123',avatar:'assets/images/sos-logo.png',role:'member',paidMember:false,collaborationAccess:false}
];
function seedDemoAccounts(){const users=SOS.read(SOS.K.users,[]);let changed=false;DEMOS.forEach(d=>{if(!users.some(u=>u.email===d.email)){users.push({...d});changed=true}});if(changed)SOS.write(SOS.K.users,users)}
seedDemoAccounts();
const show=()=>{const s=SOS.getSession();A.hidden=!!s;D.hidden=!s;if(s){document.getElementById('dashboardAvatar').src=s.avatar||'assets/images/sos-logo.png';document.getElementById('dashboardName').textContent=s.displayName;document.getElementById('dashboardEmail').textContent=`${s.email} • ${s.role}${s.paidMember?' • Paid member':''}`;const v=document.getElementById('vaultAccessText');if(v)v.textContent=s.paidMember?'Paid membership active — the full Members Vault is unlocked.':'Free membership active — member releases are available; paid-vault tracks remain locked.';let access=document.getElementById('memberSpecialAccess');if(!access){access=document.createElement('div');access.id='memberSpecialAccess';access.className='memberSpecialAccess';D.querySelector('.dashboardGrid')?.prepend(access)}access.innerHTML=`${(s.role==='admin'||s.collaborationAccess)?'<a class="memberAccessCard collabAccessCard" href="collaboration.html"><span class="accessCardIcon" aria-hidden="true">🤝</span><span class="accessCardCopy"><span class="accessCardLabel">Private workspace</span><strong>Collaboration Studio</strong><small>Projects, team chats, audio versions and production progress.</small></span><span class="accessCardAction">Open Studio <b>→</b></span></a>':''}${s.role==='admin'?'<a class="memberAccessCard adminAccessCard" href="admin.html"><span class="accessCardIcon" aria-hidden="true">⚙</span><span class="accessCardCopy"><span class="accessCardLabel">Administrator access</span><strong>Admin Hub</strong><small>Manage members, forums, content, purchases and site controls.</small></span><span class="accessCardAction">Open Admin <b>→</b></span></a>':''}`;access.hidden=!access.innerHTML.trim()}};
document.querySelectorAll('[data-auth-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-auth-tab]').forEach(x=>x.classList.toggle('active',x===b));document.getElementById('loginForm').hidden=b.dataset.authTab!=='login';document.getElementById('registerForm').hidden=b.dataset.authTab!=='register'});
document.querySelectorAll('[data-demo-login]').forEach(btn=>btn.onclick=()=>{const d=DEMOS.find(x=>x.role===btn.dataset.demoLogin);if(!d)return;const f=document.getElementById('loginForm');f.elements.email.value=d.email;f.elements.password.value=d.password;document.getElementById('loginMessage').textContent=`Loaded ${d.displayName}. Press Enter Member Area.`;f.elements.email.focus()});
document.getElementById('registerForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),email=f.get('email').toLowerCase(),users=SOS.read(SOS.K.users,[]);if(users.some(u=>u.email===email)){document.getElementById('registerMessage').textContent='That email is already registered.';return}const file=f.get('avatar'),finish=avatar=>{const u={id:crypto.randomUUID(),displayName:f.get('displayName'),email,password:f.get('password'),avatar,role:'member',paidMember:false,collaborationAccess:false};users.push(u);SOS.write(SOS.K.users,users);SOS.setSession({...u,password:undefined});SOS.toast('Account created');show()};if(file&&file.size){SOSImages.compress(file,{maxWidth:520,maxHeight:520,quality:.78,maxBytes:260*1024}).then(r=>finish(r.dataUrl)).catch(err=>{document.getElementById('registerMessage').textContent=err.message})}else finish('assets/images/sos-logo.png')};
document.getElementById('loginForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),u=SOS.read(SOS.K.users,[]).find(x=>x.email===f.get('email').toLowerCase()&&x.password===f.get('password'));if(!u){document.getElementById('loginMessage').textContent='Email or password was not found.';return}SOS.setSession({...u,password:undefined});SOS.toast(`Welcome back, ${u.displayName}`);show()};
document.getElementById('resetPassword').onclick=()=>SOS.toast('Connect Supabase email recovery to send reset links.');document.getElementById('logoutButton').onclick=()=>SOS.logout();document.getElementById('dashboardCart').onclick=()=>document.getElementById('cartDrawer').classList.add('open');show()
})();
