(()=>{
"use strict";
const host=document.getElementById("musicCommerceGrid"),notice=document.getElementById("musicVaultNotice");if(!host)return;
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const defaults=[{id:"demo-night-drive",title:"Night Drive",artist:"Seeker Of SoundZ",genre:"Electronic",price:2.99,bpm:150,musicalKey:"F Minor",description:"A cinematic electronic demo release. Replace the preview and full-file paths in Admin → Music Manager.",preview:"",full:"",artwork:"assets/images/music-featured-cover.jpg",formats:["MP3","WAV"],access:"purchase",featured:true},{id:"demo-vip-edit",title:"Frequency Unknown VIP Edit",artist:"Seeker Of SoundZ",genre:"VIP Edit",price:0,description:"Example paid-member vault release.",preview:"",full:"",artwork:"assets/images/music-featured-cover.jpg",formats:["MP3"],access:"paid"}];
let tracks=SOS.read(SOS.K.music,[]);if(!tracks.length)tracks=defaults;
const session=SOS.getSession();
function canAccess(t){if(t.access==="public")return true;if(t.access==="member")return !!session;if(t.access==="paid")return !!session?.paidMember;return false}
function label(t){return t.access==="paid"?"Paid Members":t.access==="member"?"Members":t.access==="public"?"Free Download":"Purchase"}
host.innerHTML=tracks.map(t=>`<article class="musicCommerceCard ${t.featured?'isFeatured':''}"><div class="musicCommerceArt">${t.artwork?`<img src="${esc(t.artwork)}" alt="${esc(t.title)} artwork">`:'<span>♪</span>'}<span class="musicAccessBadge">${label(t)}</span></div><div class="musicCommerceBody"><p class="sectionEyebrow">${esc(t.genre||'Original Music')}</p><h3>${esc(t.title)}</h3><p>${esc(t.description||'Original release from Seeker Of SoundZ.')}</p><div class="musicFacts">${t.bpm?`<span>${t.bpm} BPM</span>`:''}${t.musicalKey?`<span>${esc(t.musicalKey)}</span>`:''}</div>${t.preview?`<audio controls preload="none" data-title="${esc(t.title)}" data-meta="${esc(t.genre||'Original Music')} preview" src="${esc(t.preview)}"></audio>`:'<div class="audioPathHint">Add a preview path in Admin → Music Manager.</div>'}<div class="musicCommerceActions">${t.access==='purchase'?`<select data-format="${esc(t.id)}">${(t.formats?.length?t.formats:['MP3']).map(f=>`<option>${esc(f)}</option>`).join('')}</select><button class="primaryButton" data-buy-track="${esc(t.id)}">Add • $${Number(t.price||0).toFixed(2)}</button>${t.purchaseUrl?`<a class="secondaryButton musicPurchaseLink" href="${esc(t.purchaseUrl)}" target="_blank" rel="noopener">${esc(t.purchaseCta||'Open purchase page')}</a>`:''}`:canAccess(t)?`<button class="primaryButton" data-download-track="${esc(t.id)}">Access Download</button>`:`<a class="primaryButton" href="members.html">${session?'Upgrade Membership':'Sign In to Unlock'}</a>`}</div></div></article>`).join('');
notice.innerHTML=session?.paidMember?'<strong>Paid Members Vault unlocked.</strong><p>Your account can access all member and paid-member releases.</p>':session?'<strong>Signed in as a free member.</strong><p>Member releases are available, while paid vault releases require paid access.</p>':'<strong>Members Vault locked.</strong><p>Sign in on the Members page. An admin can grant paid access from Admin → Members in this local preview.</p>';
host.onclick=e=>{let b=e.target.closest('[data-buy-track]');if(b){const t=tracks.find(x=>String(x.id)===b.dataset.buyTrack);const format=host.querySelector(`[data-format="${CSS.escape(String(t.id))}"]`)?.value||'MP3';SOS.addCart({id:`music-${t.id}`,name:t.title,price:Number(t.price||0),format,type:'music'});return}b=e.target.closest('[data-download-track]');if(b){const t=tracks.find(x=>String(x.id)===b.dataset.downloadTrack);if(!canAccess(t))return;if(!t.full){SOS.toast('Add the full/download audio path in Admin → Music Manager.',{title:'Download not configured'});return}const a=document.createElement('a');a.href=t.full;a.download='';a.click();SOS.toast('Your download has started.',{title:t.title,icon:'♪'})}};
})();